//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> New { get; set; }
        public string Offer { get; set; }
        public string Source { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Category category { get; set; }
    }
}
